language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_orphaned_objects
  - drush en --yes islandora_orphaned_objects
script:
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_orphaned_objects
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_orphaned_objects
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_orphaned_objects
  - drush test-run --uri=http://localhost:8081 "Islandora Orphaned Objects"
