<?php

/**
 * @file
 * A list of orphaned Islandora objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_orphaned_objects_menu() {
  $items = array();
  $items['admin/islandora/tools/orphaned_objects/list'] = array(
    'title' => 'Islandora Orphaned Objects',
    'description' => 'List of orphaned objects.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_orphaned_objects_manage_form'),
    'access arguments' => array('manage orphaned objects'),
    'file' => 'includes/manage.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */

function islandora_orphaned_objects_permission() {
  return array(
    'manage orphaned objects' => array(
      'title' => t('Manage orphaned objects'),
      'description' => t('View a list of orphaned objects.'),
    ),
  );
}
