<?php

/**
 * @file
 * A list of orphaned Islandora objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_orphaned_objects_menu() {
  $items = array();
  $items['admin/islandora/tools/orphaned_objects/list'] = array(
    'title' => 'Islandora Orphaned Objects',
    'description' => 'List of orphaned objects.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_orphaned_objects_manage_form'),
    'access arguments' => array('manage orphaned objects'),
    'file' => 'includes/manage.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */

function islandora_orphaned_objects_permission() {
  return array(
    'manage orphaned objects' => array(
      'title' => t('Manage orphaned objects'),
      'description' => t('View a list of orphaned objects.'),
    ),
  );
}


/**
 * Implements hook_islandora_object_alter().
 */
/*
function islandora_orphaned_objects_islandora_object_alter(AbstractObject $object, array &$context) {
  module_load_include('inc', 'islandora', 'includes/utilities');
  if ($context['action'] == 'ingest') {
    $connection = islandora_get_tuque_connection();
    $enabled_solution_packs = module_invoke_all('islandora_required_objects', $connection);
    $system_objects = array();
    foreach ($enabled_solution_packs as $solution_pack_module => $solution_pack_info) {
      foreach ($solution_pack_info['objects'] as $solution_pack_object) {
        $system_objects[] = $solution_pack_object->id;
      }
    }
    if (!in_array($object->id, $system_objects) && !user_access('bypass inactive object state')) {
      $object->state = 'I';
    }
  }
} */
